version: "3.9"
services:
  postgres:
    container_name: wompi_db.postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - data_postgres:/var/lib/postgresql/data
volumes:
  data_postgres: